### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Challenge-20#3]
Create a footer for this website.

**Comment by abitsalihu** [comment]
@Rakesh9100 I would like to help with your issue, what would you like the content inside the footer to be?

**Comment by Rakesh9100** [comment]
> @Rakesh9100 I would like to help with your issue, what would you like the content inside the footer to be?

Hey man, this repo is just the part of an open source challenge by scaler and hence not for contributing.
